# يخبر هذا السطر Netlify أنه لا يوجد أمر بناء (build command) لتشغيله.
[build]
  command = ""
  publish = "."

# هذه قاعدة إعادة توجيه قياسية للتطبيقات أحادية الصفحة (SPAs).
# إنها تضمن أن أي وصول مباشر إلى رابط معين (مثل مشاركة خطة رحلة)
# سيقوم بعرض ملف index.html بشكل صحيح، مما يسمح للتطبيق بالعمل.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200